# Generated by Django 4.0.5 on 2022-06-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_title_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Title',
        ),
        migrations.AddField(
            model_name='post',
            name='Author',
            field=models.CharField(default='some string', max_length=200),
        ),
    ]
